services:

  Ewll\MailerBundle\Mailer:
    arguments:
      - '@Ewll\MysqlMessageBrokerBundle\MessageBroker'
      - '@ewll.db.repository-provider'
      - '@translator'
      - '@twig'
      - '@logger'
      - '%ewll_mailer.host%'
      - '%ewll_mailer.port%'
      - '%ewll_mailer.secure%'
      - '%ewll_mailer.user%'
      - '%ewll_mailer.pass%'
      - '%ewll_mailer.smtp_auth%'
      - '%ewll_mailer.sender_email%'
      - '%ewll_mailer.sender_name%'

  Ewll\MailerBundle\SendLetterDaemon:
    parent: Ewll\MysqlMessageBrokerBundle\AbstractDaemon
    arguments: ['@logger', '@Ewll\MysqlMessageBrokerBundle\MessageBroker', '@Ewll\MailerBundle\Mailer']
    tags:
      - { name: 'console.command', command: 'ewll:mailer:daemon:send-letter' }
      - { name: monolog.logger, channel: mailer }
